steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/t2image', '.']
    dir: backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/t2image']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    secretEnv: ['STABILITY_API_KEY']
    args:
      [
        'run', 'deploy', 't2image',
        '--image', 'gcr.io/$PROJECT_ID/t2image',
        '--region', 'us-central1',
        '--allow-unauthenticated',
      ]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/stability-api-key/versions/latest
      env: STABILITY_API_KEY
options:
  logging: CLOUD_LOGGING_ONLY